# **Tarea Nº 1**

Curso:          Fundamentos de Programación en Python para Macroeconomía y Finanzas     
Profesor:       Victor Fuentes Campos     

- Fecha y hora de entrega: Jueves 4 de enero, 11:59pm
- Agregue los nombres de las personas con las que discutió esta tarea: ____ Armando Paredes ______
- Envíe su tarea haciendo el `push` de su código a su repo en GitHub Classroom: 

# 1. Git


a. Commit, Push, Pull

Instrucciones:
1. Cada miembro del equipo debe clonar el repo de su tarea en su computadora
1. Luego, en el branch master (`main`), el integrante Nº 1 cambia el nombre del archivo `.ipynb` a `tarea_1.ipynb`
1. Usando GitHub Desktop, el integrante Nº 2 notará que hay cambios en el repo. Por lo tanto, hará el `pull` de la nueva versión del repo. Ahora ambos tiene el archivo con el nombre apropiado en sus computadoras

*Este ejercicio se calificará directamente en GitHub*

b. Merge conflicts (opcional)

1. El integrante Nº 1 abre un branch nuevo `merge_conflict_practice_1`. En el archivo `tarea_1.ipynb` reemplazará "Armando Paredes" por su nombre. Luego, hará `commit`y `push` de a GitHub. (En Github Desktop se llama `publish`)
1. El integrante Nº 2 abre un branch nuevo `merge_conflict_practice_2`. En el archivo `tarea_1.ipynb` reemplazará "Armando Paredes" por su nombre. Luego, hará `commit`y `push` de a GitHub. (En Github Desktop se llama `publish`)
1. El integrante Nº 1 hará un `pull request`
1. El integrante Nº 2 hará el `review` del `pull request`, aceptará los cambios de su compañero y hará `merge` del branch al `master`. ¡Listo, completaste tu primer pull request!
1. El integrante Nº 2 hará un `pull request`
1. El integrante Nº 1 hará el `review` del `pull request` y habrá un `merge conflict` poeque ambos están cambiando la misma línea de código. Ajuste el archivo y complete el `merge``
Cambie de roles y fuerce un `merge conflict` con una sección diferente del archivo `tarea_1.ipynb` (Fecha de entrega, nombre del curso, etc.)
1. Explique muy brevemente porque se generó el `merge conflict`

*Respuesta: ______________________________*

# 2. Variables

Considere la siguiente información como punto de partida y complete los espacios en blanco

In [4]:
monthly_savings = 10
num_months = 12
intro = "Hello! How are you?"

a. Calculate year_savings using monthly_savings and num_months


In [88]:
# Calculate the product of monthly_savings and num_months
year_savings = monthly_savings * num_months

print("Yearly Savings:", year_savings)

Yearly Savings: 120


b. Print the type of year_savings

In [89]:
# What do you think the resulting type will be? Find out by printing out the type of year_savings.
type(year_savings)

int

c. Assign sum of intro and intro to doubleintro

In [91]:
# Calculate the sum of intro and intro and store the result in a new variable doubleintro.
doubleintro = intro + intro

d. Print out doubleintro

In [92]:
# Print out doubleintro. Did you expect this?
print("Double Intro:", doubleintro)

Double Intro: Hello! How are you?Hello! How are you?


# 3. Lists

Considere la siguiente información como punto de partida y complete los espacios en blanco

In [9]:
import numpy as np
f_list = ["Brazil", np.nan , np.nan, "Austria", "Germany", np.nan, "Pakistan", "np.nan", np.nan ]
text1 = ['My', 'new', 'teacher', 'assistant', 'is', 'so', 'boring.']
p1_list = [ 2 , 3, 4, 5 , 6 ]
values1 = [ 86, 86, 85, 85, 85, 83, 23, 0, 84, 1, 91 ]
last_and_name = [ "CORNEJO SANCHEZ, CHRISTIAN SANTOS", "ORELLANA QUISPE, CRISTIAN NASSER", "MORALES CHOQUEHUANCA, ANGELICA KARINA", "GUIMARAY RIBEYRO, JOSE ROBERTO", "CAMACHO GAVIDIA, ABEL FERNANDO", "TINTAYA ORIHUELA, MEIR ALVARO", "CHAVEZ MARTINEZ, JOSELIN ALEXANDRA", "FIGUEROA MURO, LEONEL ARTURO", "GOMEZ CRIBILLERO, JOSE FELIPE", "PALOMINO SEGUÍN, AFRANIA", "LUZON CUEVA, BIANCA MARIETTE", "SUAÑA ZEGARRA, ADRIAN ANDRE", "SOTO POMACHAGUA, DORKAS YOMIRA JHERMY", "FIORENTINO MARTINEZ, LADY ALY", "LAMA MAVILA, HECTOR ANDRE", "MEZA HINOJO, GUSTAVO", "LOZADA MURILLO, PERSEO MARCELO", "ZAMBRANO JIMENEZ, MIGUEL ALONZO", "JACOBS LUQUE, NICOLAS", "VIDAL VIDAL, ROCIO GABRIELA", "TORRES ANICAMA, JANE CAMILA", "LOPEZ ESTRADA, MARIA ELISA", "BOYCO ORAMS, ALEJANDRO", "DIAZ BERROSPI, KARLINE ROSMELI", "RIEGA ESCALANTE, STEPHY ROSARIO", "LEVANO TORRES, VALERIA CECILIA", "ESQUIVES BRAVO, SEBASTIAN RENATO", "PEREZ GONZALES, JUAN CARLOS", "OTERO MAGUIÑA, MARIANA", "CLAVO CAMPOS, ANDREA BRIZETH", "AGUILAR GARCIA, ERICK JOSUE", "CALDAS VELASQUEZ, JOSUE DANIEL", "SALAS NUÑEZ BORJA, FABIO MANUEL", "PIZARRO VILLANES, FERNANDA NICOLLE", "QUILLATUPA MORALES, ANGELA ADELINA", "HUANCAYA IDONE, CESAR DANTE", "CALVO PORTOCARRERO, GABRIELA ISABEL", "IBAÑEZ ABANTO, ANGEL MAURICIO", "MELÉNDEZ APONTE, JUAN DIEGO", "CRISTIAN SERRANO, ARONE", "HINOJOSA CAHUANA, PERCY ALBERTH", "ANGLAS GARCÍA, KEVIN ARTURO", "ALDAVE ACOSTA, CESAR ERNESTO", "NÚÑEZ HUAMÁN, CÉSAR AGUSTO", "OBREGON HUAMAN, DIANA EDITH", "SOTO PACHERRES, RODRIGO FRANCO", "INGARUCA RIVERA, GRETTEL ALEXANDRA", "ROJAS HUAMAN, ROSA ANGELA", "NEYRA SALAS, DANTE OMAR", "HUERTA ESPINOZA, YAJAIRA ALEXANDRA", "HUANCA MARTINEZ, JORGE ALBERTO", "FLORES CADILLO, ALEXIS" ]
emails = ["cscornejo@pucp.edu.pe", "orellana.cn@pucp.edu.pe", "karina.morales@pucp.edu.pe", "a20083223@pucp.pe", "abel.camacho@pucp.pe", "mtintaya@pucp.edu.pe", "joselin.chavez@pucp.edu.pe", "a20105737@pucp.pe", "jfgomezc@pucp.pe", "afrania.palomino@pucp.pe", "luzon.bianca@pucp.pe", "adrian.suanaz@pucp.pe", "soto.y@pucp.edu.pe", "a20132766@pucp.pe", "andre.lama@pucp.edu.pe", "gustavo.meza@pucp.edu.pe", "pmlozada@pucp.edu.pe", "m.zambranoj@pucp.edu.pe", "nicolas.jacobs@pucp.edu.pe", "gvidal@pucp.edu.pe", "jane.torres@pucp.edu.pe", "m.lopez@pucp.edu.pe", "alejandro.boyco@pucp.edu.pe", "a20167070@pucp.edu.pe", "riega.stephy@pucp.edu.pe", "vlevanot@pucp.edu.pe", "sesquives@pucp.edu.pe", "perez.juanc@pucp.edu.pe", "mariana.otero@pucp.edu.pe", "aclavo@pucp.edu.pe", "a20182474@pucp.edu.pe", "josue.caldas@pucp.edu.pe", "fabio.salas@pucp.edu.pe", "fernanda.pizarro@pucp.edu.pe", "aquillatupa@pucp.pe", "", "", "", "", "", "f0873079@pucp.edu.pe", "", "", "", "", "", "", "", "", "", "", "flores.alexis@pucp.edu.pe", ]

a. Show the indices of the `np.nan`` values in the `f_list` list. We want to see this output: *The indices 1, 2, 5, 8 have np.nan values*. Hint: Use print function and f-strings to insert the indices values.

In [81]:
# Show indices for np.nan values
nan_indices = []

#iterar sobre la lista y encontrar los índices de np.nan
for i, value in enumerate(f_list):
    if isinstance(value, float) and np.isnan(value):
        nan_indices.append(i)

indices_str = ', '.join(map(str, nan_indices))
print(f"{indices_str} tienen valores np.nan.")


1, 2, 5, 8 tienen valores np.nan.


b. Replicate 4 times the values of the list `p1_list`. We expect an ouput like this: [ 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5]. Hint: Use multiplication function in listsand see the output.

In [82]:
# Replicates p1_list
replicated_list = p1_list * 4

print(replicated_list)

[2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6]


c. Print the length of `f_list`. **Hint: Length function**

In [83]:
# Lenngth of f_list
length = len(f_list)
print(length)


9


d. Print `My new teacher assistant is so boring.` using `text1` list. **Hint: Use the [`join` function](https://stackoverflow.com/questions/493819/why-is-it-string-joinlist-instead-of-list-joinstring)**

In [84]:
# Printing
sentence = ' '.join(text1)
print(sentence)


My new teacher assistant is so boring.


e. Using `values1`, print <br>
`The max value of values1 is 86 and is located in the 0 index. ` <br>
`The min value of values1 is 0 and is located in the 7 index. ` <br> **Hint: Use the `f-string`, `min`, and `max` functions.**
<br>

In [85]:
# Printing
max_value = max(values1)
max_index = values1.index(max_value)

min_value = min(values1)
min_index = values1.index(min_value)

print(f"The max value of values1 is {max_value} and is located in the {max_index} index.")
print(f"The min value of values1 is {min_value} and is located in the {min_index} index.")

The max value of values1 is 91 and is located in the 10 index.
The min value of values1 is 0 and is located in the 7 index.


f. Get two lists: `given_names` and `last_names` using `last_and_name` list. **Hint: Use `map` and `split`.**

In [86]:
# Two lists
given_names, last_names = zip(*(name.split(' ', 1) for name in last_and_name))

print("Given Names:", given_names)
print("Last Names:", last_names)

Given Names: ('CORNEJO', 'ORELLANA', 'MORALES', 'GUIMARAY', 'CAMACHO', 'TINTAYA', 'CHAVEZ', 'FIGUEROA', 'GOMEZ', 'PALOMINO', 'LUZON', 'SUAÑA', 'SOTO', 'FIORENTINO', 'LAMA', 'MEZA', 'LOZADA', 'ZAMBRANO', 'JACOBS', 'VIDAL', 'TORRES', 'LOPEZ', 'BOYCO', 'DIAZ', 'RIEGA', 'LEVANO', 'ESQUIVES', 'PEREZ', 'OTERO', 'CLAVO', 'AGUILAR', 'CALDAS', 'SALAS', 'PIZARRO', 'QUILLATUPA', 'HUANCAYA', 'CALVO', 'IBAÑEZ', 'MELÉNDEZ', 'CRISTIAN', 'HINOJOSA', 'ANGLAS', 'ALDAVE', 'NÚÑEZ', 'OBREGON', 'SOTO', 'INGARUCA', 'ROJAS', 'NEYRA', 'HUERTA', 'HUANCA', 'FLORES')
Last Names: ('SANCHEZ, CHRISTIAN SANTOS', 'QUISPE, CRISTIAN NASSER', 'CHOQUEHUANCA, ANGELICA KARINA', 'RIBEYRO, JOSE ROBERTO', 'GAVIDIA, ABEL FERNANDO', 'ORIHUELA, MEIR ALVARO', 'MARTINEZ, JOSELIN ALEXANDRA', 'MURO, LEONEL ARTURO', 'CRIBILLERO, JOSE FELIPE', 'SEGUÍN, AFRANIA', 'CUEVA, BIANCA MARIETTE', 'ZEGARRA, ADRIAN ANDRE', 'POMACHAGUA, DORKAS YOMIRA JHERMY', 'MARTINEZ, LADY ALY', 'MAVILA, HECTOR ANDRE', 'HINOJO, GUSTAVO', 'MURILLO, PERSEO MARCELO

g. (Opcional) Give only the last names of students who do not have email. Use the `emails` and `last_names` listt. **Hint: Use `map` and `split`.**

In [87]:
# List of of those who do not have email

# lista con los apellidos de los estudiantes que no tienen correo electrónico
last_names_no_email = []

# iterar sobre las listas 'emails' y 'last_names' al mismo tiempo
for email, last_name in zip(emails, last_names):
    # Verificar si el estudiante no tiene correo electrónico
    if not email:
        # Agregar el apellido a la lista 'last_names_no_email'
        last_names_no_email.append(last_name)

# Imprimir la lista de apellidos de estudiantes sin correo electrónico
print("Last Names of Students without Email:", last_names_no_email)


Last Names of Students without Email: []


# 4.   Tuple


Considere la siguiente información como punto de partida y complete los espacios en blanco

In [38]:
tuple1 = ("Orange", [10, 20, 30], (5, 15, 25))
tuple2 = ([7, 8], [9, 1], [10, 7])

1. Print the first item of the second item of tuple1 object

In [18]:
# Print
print(tuple1[1][0])

10


2. Print the last item of the tuple1 object

In [32]:
# Print
print(tuple1[-1][-1])

25


3. Change the value "orange" for "pink grapefruit". Comment the output

In [33]:
# Change value
tuple1 = list(tuple1)
tuple1[0] = "pink grapefruit"
tuple1 = tuple(tuple1)
tuple1

#Las tuplas son inmutables, por lo que para modificar una, 
#debes convertirla en una lista, realizar los cambios y 
#luego convertirla nuevamente en una tupla.

('pink grapefruit', [10, 20, 30], (5, 15, 25))

4. Print the length of tuple1

In [34]:
# Print
len(tuple1)

3

5. Sum all the elements of tuple2 and describe your steps and explain each of them. Hint: Use map function.


In [42]:
tuple2 = list(tuple2)

# use map and sum to get the sum of each sublist
sums = tuple(map(sum, tuple2))

# Step 3: Convert the result back to a tuple
tuple2 = tuple(sums)

# Print the result
print(tuple2)

(15, 10, 17)


6. (Opcional) Generate a new tuple object named as tuple3 with the half values of tuple2. This tuple should be similar as tuple2, tuple of lists. Hint: Use map funciont.

In [43]:
tuple2 = ([7, 8], [9, 1], [10, 7])

# Use map to create tuple3 with half values
tuple3 = tuple(map(lambda sublist: [x // 2 for x in sublist], tuple2))

print(tuple3)

([3, 4], [4, 0], [5, 3])


# 5. Strings

Considere la siguiente información como punto de partida y complete los espacios en blanco

In [75]:
str1 = 'I am                            too                                                        old'
emails = ["cscornejo@pucp.edu.pe", "orellana.cn@pucp.edu.pe", "karina.morales@pucp.edu.pe", "a20083223@pucp.pe", "abel.camacho@pucp.pe", "mtintaya@pucp.edu.pe", "joselin.chavez@pucp.edu.pe", "a20105737@pucp.pe", "jfgomezc@pucp.pe", "afrania.palomino@pucp.pe", "luzon.bianca@pucp.pe", "adrian.suanaz@pucp.pe", "soto.y@pucp.edu.pe", "a20132766@pucp.pe", "andre.lama@pucp.edu.pe", "gustavo.meza@pucp.edu.pe", "pmlozada@pucp.edu.pe", "m.zambranoj@pucp.edu.pe", "nicolas.jacobs@pucp.edu.pe", "gvidal@pucp.edu.pe", "jane.torres@pucp.edu.pe", "m.lopez@pucp.edu.pe", "alejandro.boyco@pucp.edu.pe", "a20167070@pucp.edu.pe", "riega.stephy@pucp.edu.pe", "vlevanot@pucp.edu.pe", "sesquives@pucp.edu.pe", "perez.juanc@pucp.edu.pe", "mariana.otero@pucp.edu.pe", "aclavo@pucp.edu.pe", "a20182474@pucp.edu.pe", "josue.caldas@pucp.edu.pe", "fabio.salas@pucp.edu.pe", "fernanda.pizarro@pucp.edu.pe", "aquillatupa@pucp.pe"]

1. Drop the duplicated blank spaces in `str1`. Do not use the regular expresions. Do not use the code shown in class. Explain your steps.**Hint: Use `split` method and `join` function.**

In [76]:
# Drop duplicated blank spaces
words_list = str1.split()
words_list = filter(lambda x: x.strip() != '', words_list)
words_list = ' '.join(words_list)
words_list

'I am too old'

2. Get the number of letters in the string .**Hint: Use `len`function.**

In [77]:
# Number of letters
words_list = str1.split()
words_list = filter(lambda x: x.strip() != '', words_list)
words_list = ''.join(words_list)
words_list = len(words_list)
words_list

9

3. (Optional) Get the number of blank spaces (all of them) in the string .**Hint: Use `len`function.**

In [79]:
spaces = str1.count(' ')

print(spaces)

85


# 6. NumPy

Considere la siguiente información como punto de partida y complete los espacios en blanco

In [53]:
import numpy as np
from scipy import stats

In [55]:
prueba1 = np.random.randint(0,10,500)
prueba1


array([1, 7, 9, 2, 2, 3, 2, 0, 7, 8, 8, 9, 3, 2, 3, 6, 8, 7, 8, 3, 9, 8,
       4, 8, 0, 0, 9, 0, 1, 0, 3, 3, 6, 3, 0, 6, 4, 3, 4, 6, 4, 3, 9, 3,
       7, 8, 7, 8, 2, 0, 5, 9, 5, 7, 6, 0, 3, 9, 2, 4, 3, 1, 9, 3, 9, 0,
       4, 4, 6, 6, 8, 9, 2, 1, 7, 9, 7, 1, 6, 9, 4, 4, 5, 6, 3, 1, 7, 6,
       9, 0, 5, 4, 7, 0, 0, 5, 3, 2, 9, 0, 9, 2, 9, 8, 0, 0, 1, 9, 7, 7,
       9, 8, 1, 2, 5, 9, 5, 7, 3, 4, 1, 4, 4, 6, 2, 0, 2, 6, 8, 6, 4, 4,
       4, 6, 8, 9, 4, 8, 2, 8, 5, 7, 8, 2, 8, 6, 0, 6, 7, 7, 7, 5, 1, 0,
       4, 2, 2, 8, 9, 4, 7, 8, 0, 1, 9, 0, 1, 6, 2, 8, 4, 4, 7, 5, 6, 6,
       8, 8, 5, 3, 0, 4, 8, 5, 5, 4, 3, 6, 0, 1, 3, 4, 6, 2, 6, 4, 5, 5,
       9, 0, 8, 0, 4, 9, 5, 6, 5, 8, 4, 3, 9, 3, 1, 4, 1, 7, 4, 1, 2, 1,
       4, 5, 5, 0, 0, 3, 0, 2, 4, 0, 8, 2, 5, 0, 9, 5, 9, 5, 2, 1, 3, 2,
       2, 0, 6, 4, 0, 4, 6, 7, 6, 2, 7, 5, 4, 5, 9, 7, 4, 8, 1, 6, 8, 9,
       4, 0, 5, 4, 1, 0, 4, 4, 8, 7, 6, 7, 0, 4, 6, 2, 8, 2, 6, 8, 8, 9,
       0, 3, 9, 1, 3, 9, 5, 1, 8, 5, 7, 4, 5, 3, 4,

In [29]:
prueba2 = np.arange(50)
np.random.shuffle(prueba2)
prueba2

array([12, 38, 25, 41, 42, 39, 24, 45, 28, 18, 43, 49, 17, 15, 31, 44, 37,
       47, 10, 34, 26,  9, 14,  4, 16,  7, 35, 46, 19,  5, 13, 21, 36, 20,
        1,  3, 32,  2, 30, 22, 11, 23,  0, 33, 29,  6,  8, 40, 27, 48])

a. Find the most frequent value in the prueba1 array?

In [48]:
# Most frequent value

In [60]:
A = stats.mode(prueba1) #.mode[0]
A

ModeResult(mode=4, count=69)

b. Convert the 1D array prueba2 to a 2D array with 5 rows

In [61]:
# Reshape
# Assuming you have the prueba2 array
prueba2 = np.arange(50)
np.random.shuffle(prueba2)

# Reshape to a 2D array with 5 rows
prueba2_2d = np.reshape(prueba2, (5, -1))

print("Original 1D array:")
print(prueba2)
print("\nReshaped 2D array with 5 rows:")
print(prueba2_2d)


Original 1D array:
[ 5 38 29 15 10 48 25  8 33 32 36  9  4  3 49 44 17 19 31 46 24 14  0 23
 16 18 45 39 28 37 11 43  1 13 26  7  2 47 42 30 12 21 20 41 34 27 35 22
  6 40]

Reshaped 2D array with 5 rows:
[[ 5 38 29 15 10 48 25  8 33 32]
 [36  9  4  3 49 44 17 19 31 46]
 [24 14  0 23 16 18 45 39 28 37]
 [11 43  1 13 26  7  2 47 42 30]
 [12 21 20 41 34 27 35 22  6 40]]
